# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  sportDb:
    image: mongo

  sport:
    image: aspnetcore5
    build:
      context: .
      dockerfile: ./Dockerfile

volumes: 
  mongo_data:
